### ISSUE TITLE
No clue how to set this up on windows

### ISSUE THREAD

**Issue by SCFDMerch** [JamesIves/perforce-commit-discord-bot#14]
Hi im trying to set this up with my discord channel and have no clue how to go about setting this up.
Specifically having troubles with these parts
2. Save the webhook URL as an environment variable called DISCORD_WEBHOOK_URL.

I have no clue what you mean by an environment variable and what to do with it.

3. The service requires access to the p4 changes command in the terminal, your bot should be installed somewhere where it can automatically perform this command without the session expiring. Once suitable access has been provided you'll need to run $ pip install -r requirements.txt followed by $ python app.py to initialize it.

Where do i execute these commands, i have no clue where i am supposed to execute them from and no idea have to give whatever is meant to access this suitable access.

I think you could have made things a little clearer and easier to understand, i know nothing about discord bots and am just trying to set this up and i am having some real difficulty's understanding this

Thanks in advance.

**Comment by JamesIves** [comment]
The second step is referring to a variable that is defined on your system, it allows things like this Python script to access defined data (the URL) without needing to write it into code. I'm not a Windows user, but on OSX you can write `export DISCORD_WEBHOOK_URL=https://` in to the terminal to define one. This video might be helpful, but there's probably other ways to achieve the same thing: https://www.youtube.com/watch?v=bEroNNzqlF4. 

Alternatively you can fork the project and edit this line: https://github.com/JamesIves/perforce-commit-discord-bot/blob/master/app.py#L50 to read the following

```python
DISCORD_WEBHOOK_URL = 'https://discord.gg/replacemewithyourrul'
```

The third step is talking about your Perforce server command line. In your terminal there's a number of commands you can run on the server you're hosting Perforce on, one of which is `p4 changes`. In order for the bot to actually see the changes to the Perforce commit log you need to execute the Python script in a location where you yourself can run this command. The way to test this would be by logging into your server, going to your terminal, typing in `p4 changes`, if it works then run the Python script. This isn't the most secure approach to this, but that's all I had time to come up with when I initially wrote this. 

The README (and this script in general) requires you to have some prior knowledge with Python and Perforce, which admittedly is a weird combination. Generally speaking I wouldn't use this if you're not familiar with the concepts as you could end up creating some security issues with your Perforce instance.

I'm open to suggestions on how to improve the documentation if you'd like to open a PR.

**Comment by SCFDMerch** [comment]
Ok i manage to get it setup thanks to the things you said to try, that enviornment variable thing really cleared it up for me.

i think its probs a good idea to mention to install python and to make sure its setup correctly, i had to fully reinstall it to get the pip commands to work, and had to look up alot of the commands to actually run the stuff but overall not too hard once you actually know how to do it

But for anyone in the future who needs to know what to do first thing you need to do is download python and install it, and make sure that cmd recognises the python command and pip install command
then just change the environment variable really easy when you know how then pretty much just follow the rest of the guide, the commands just input them without the $ symbol in front of them
