### ISSUE TITLE
git clone issue

### ISSUE THREAD

**Issue by Miscni** [JamesIves/perforce-commit-discord-bot#2]
Trying to use this command here

`git clone -b develop --single-branch https://github.com/JamesIves/perforce-commit-discord-bot.git
`
```
Cloning into 'perforce-commit-discord-bot'...
warning: Could not find remote branch develop to clone.
```

I'm totally newbie with discordbot and git, but I tryed to use this setup here.
https://twentysix26.github.io/Red-Docs/red_install_debian/

Only changes this here 
`git clone -b develop --single-branch https://github.com/Twentysix26/Red-DiscordBot.git`

to 

`git clone -b develop --single-branch https://github.com/JamesIves/perforce-commit-discord-bot.git`

I can download it fine manully. But not with SSH

**Comment by JamesIves** [comment]
There's no branch called develop, I'm also unsure what this has to do with that other repo?
