### ISSUE TITLE
Littles changes

### ISSUE THREAD

**Issue by Megurine** [JamesIves/perforce-commit-discord-bot#4]
Hi, I have changed some things from your code : 

`p4_changes = subprocess.Popen('p4 changes -t -m 1 -l', stdout=subprocess.PIPE, shell=True)`
The -l give the entire description, its more readable and clear.

`output = p4_changes.stdout.read().decode("ISO-8859-1")`
Prevent the error on decode with utf-8 with accents or stranges characters (I'm french ^^)

**Comment by Megurine** [comment]
And a condition for low uploads : 
` if "*pending*" in output:
    return `''``

**Comment by JamesIves** [comment]
@Megurine Feel free to open a pull request!

**Comment by JamesIves** [comment]
Made these changes, they are now tagged in the master branch.
