### ISSUE TITLE
Use crontabs as opposed to keeping the process open

### ISSUE THREAD

**Issue by mark-rodgers** [JamesIves/perforce-commit-discord-bot#8]
It would be nice if we could feed app.py an argument, which when set instead of keeping the process open it just checks once then pushes any changes to webhook then quits. This way instead of leaving the process open 24/7 people can just setup a cron and have it set to run at whatever frequency they want which will run the app, push any changes to discord then exit

**Comment by JamesIves** [comment]
Are you referring to doing the `p4 changes` check outside of the process of this script?
